import type { Stage } from './training-model';
import type { Material } from './business-workspace';
export type GuidedUnit = { title: string; outcome: string; stages: Stage[] };
export const LEAD_MATERIALS: Record<string, Material> = Object.fromEntries([
  ['journey', 'How the service works', 'DEMONSTRATION · Fictional cleaning business\n\nADVERT\n“Spend your weekend doing something you enjoy. Ask about a home clean.”\n↓\nENQUIRY PAGE\nVisitor asks for a quote and chooses how to be contacted.\n↓\nBUSINESS FOLLOW-UP\nThe cleaner checks location, availability and requirements, then quotes.\n\nYour service builds and checks this journey. An enquiry is not a booked job.'],
  ['customer', 'A completed customer example', 'FICTIONAL EXAMPLE · Bright Home Cleaning\n\nCustomer: a local cleaner with room for two more weekly jobs.\nProblem: irregular enquiries and missed follow-up while working.\nUseful service: one clear advert, a simple quote-request page and a follow-up checklist.\nSuccess to measure: relevant enquiries, response time and quotes sent.\nFirst check: can the business actually serve more customers?'],
  ['advert', 'Your sample advert', 'DEMONSTRATION ONLY · Not a real campaign\n\nA cleaner home. A weekend back.\nRegular home cleaning in your local area.\nTell us your postcode and the kind of clean you need. The cleaning business will confirm availability and send a quote.\n\nButton: Request a quote\nVisual: a tidy room using your own or licensed imagery.\nNo invented reviews, prices, credentials or results.'],
  ['page', 'Enquiry page mock-up', 'DEMONSTRATION ONLY\n\nHeadline: Ask about home cleaning near you\nForm: Name · Postcode · Type of clean · Preferred contact method · Contact detail\nButton: Request a quote\nNotice: Bright Home Cleaning will use these details to answer this request. Add the real business privacy notice before publishing. Do not add people to marketing lists by default.\n\nAfter submission: “Request received. The cleaner will confirm availability.”\nBusiness checklist: check service area → contact as requested → clarify the job → quote → record the outcome.'],
  ['scope', 'Your starter pilot offer', 'DRAFT PILOT · Agree terms before any work or spending\n\nGoal: test a small enquiry journey for a local cleaning business.\nDeliverables: one advert concept, one enquiry-page draft, a manual follow-up checklist and a weekly summary.\nDuration: a two-week pilot after approval.\nBusiness supplies: accurate service details, approved images, privacy information and someone to answer enquiries.\nAgree separately: service fee, approved ad budget, account access, dates and cancellation terms.\nNo guaranteed enquiry count, sales or return on spend. Nothing launches without business approval.'],
  ['opener', 'Your cold-call opener', 'Hi, I’m [your name]. This is a business call about cleaning enquiries. Is now an okay time for a twenty-second explanation?\n\nI’m preparing a small service that connects an advert to a quote-request page and a clear follow-up process. Are you currently looking for more cleaning jobs?\n\nIf yes: Would a short conversation about your service area and capacity be useful?\nIf no: Understood. Thank you for your time. I won’t follow up.\n\nDelivery: speak slowly, pause after the permission question, and listen. Do not imply an existing relationship.'],
  ['objection', 'Practise one objection', '“We already get enough work.”\n“That makes sense. I won’t take more of your time. Thank you.”\n\n“We tried adverts and they didn’t work.”\n“I understand. Was the difficulty getting relevant enquiries, or turning them into jobs?”\nOnly continue if they want to talk.\n\n“Send something.”\n“What would be useful, and which business address should I use? May I follow up, and when?”\nDo not treat this as permission for repeated messages.'],
  ['followup', 'Your agreed follow-up', 'Hi, I’m [your name]. We spoke about cleaning enquiries and agreed I could call at this time. Is it still convenient?\n\nThe pilot draft covers one advert, an enquiry page and a follow-up checklist. Would you like to talk through your service area and availability?\n\nIf they decline: Thank you. I won’t contact you again.\nIf follow-up was not agreed, choose another eligible business instead. Never invent an agreement.'],
  ['discovery', 'A short discovery agenda', '1 · Capacity: Which cleaning services and areas can you take on?\n2 · Current process: How do enquiries arrive, and who answers them?\n3 · Fit: What makes an enquiry useful or unsuitable?\n4 · Scope: Explain the small pilot and its limitations.\n5 · Next step: Summarise what was agreed and ask whether a draft proposal is useful.\n\nPractice example: Bright Home serves two nearby postcodes, has two weekly slots, and the owner replies each afternoon.'],
  ['proposal', 'Your pilot proposal', 'DRAFT · LOCAL CLEANING ENQUIRY PILOT\n\nFor: [business name]\nPrepared by: [your name]\nObjective: test an enquiry journey for an agreed service area.\nScope: one advert concept, one page draft, follow-up checklist and weekly report. One revision round.\nClient responsibilities: approve claims and budget; supply licensed assets; handle enquiries and quotes; provide privacy information.\nYour responsibilities: prepare drafts, test the journey, document changes and report accurately.\nTo agree: fee, separate ad spend cap, payment timing, dates, access permissions and cancellation.\nNo guaranteed sales or lead volume. Approval required before publication or spending.'],
  ['report', 'Mock delivery and results', 'SIMULATED DATA · NOT REAL CLIENT RESULTS\n\nDelivery check: approve advert → test form with fictional details → check the request reaches the business → check follow-up responsibilities → approve launch separately.\n\nSample weekly report\nSpend: 100 sample currency units\nEnquiries: 10\nRelevant enquiries: 6\nQuotes sent: 4\nBooked jobs: 2\nCost per enquiry: 10\nCost per relevant enquiry: about 16.67\n\nThese invented numbers teach reporting; they predict nothing. Separate enquiries from customers. Next improvement: investigate why four enquiries were unsuitable before changing spend.'],
].map(([id, title, text]) => [id, { id: `lead-${id}`, title, text, version: 1 }]));

export function leadGenerationUnits(niche = 'Local cleaning businesses'): GuidedUnit[] {
  const task = (title: string, material: string, steps: string[], extra: Partial<Stage> = {}): GuidedUnit => ({ title, outcome: steps[0], stages: [{ id: 'guided-action', type: 'action', title, prompt: '', steps, alternative: 'Your place is saved. Return when ready.', material: LEAD_MATERIALS[material], ...extra } as Stage] });
  return [
    task('See how lead generation works', 'journey', ['Follow the example from advert to enquiry to business follow-up.', `Your starting niche: ${niche}. Save the example for your project.`, 'Notice the difference between an enquiry and a paying customer.']),
    task('Understand your first customer', 'customer', ['Read the completed business example.', 'Look at its spare capacity and missed follow-up problem.', 'Save this customer example as your starting reference.']),
    task('Adapt your demonstration advert', 'advert', ['Open the supplied advert and save your version.', 'Replace the service area with an area your chosen niche serves.', 'Keep the demonstration label. Do not publish it as a real business advert.']),
    task('Walk through the enquiry page', 'page', ['Read the mock page from headline to confirmation.', 'Follow the example request through the business checklist.', 'Save the page example. No website or purchase is needed.']),
    task('Prepare a small pilot offer', 'scope', ['Open the ready-made pilot scope.', 'Save your version with the service you intend to offer.', 'Keep pricing and spend subject to agreement. Promise the work, never sales results.']),
    task('Find three suitable businesses', 'customer', ['Find a public business website for a cleaner with a clear service area.', 'Check that the business offers the service your sample covers.', 'Save three businesses and their public contact sources below.'], { workflow: 'prospects' }),
    task('Practise your call opener', 'opener', ['Read the opener once, at a comfortable pace.', 'Start the practice stopwatch and say it aloud. Pause after the opening question.', 'Repeat once with your name. No recording or assessment.'], { practice: true }),
    task('Make your first manual call', 'opener', ['Choose your calling regions and review the contact guidance.', 'Choose an eligible business and make one manual call.', 'After the call, log what actually happened. A cancelled call is not an attempt.'], { workflow: 'call' }),
    task('Practise an objection response', 'objection', ['Read the supplied objection examples.', 'Use the stopwatch to practise one response aloud.', 'Practise ending politely when the business declines.'], { practice: true }),
    task('Make an appropriate follow-up', 'followup', ['Choose a business that agreed a follow-up, at the agreed time.', 'If none agreed, use the opener with a different eligible business.', 'Record the actual outcome after one manual call.'], { workflow: 'call' }),
    task('Complete a small call session', 'opener', ['Settle into your chosen time budget.', 'Make up to three manual attempts. Stop when your budget ends; one honest attempt is enough.', 'Record each outcome. Do not call a declined prospect again.'], { workflow: 'call-session' }),
    task('Practise the discovery conversation', 'discovery', ['Open the supplied discovery agenda.', 'Walk through the fictional cleaning example aloud, or use an arranged conversation.', 'Practise a clear next step without promising results.'], { practice: true }),
    task('Prepare your pilot proposal', 'proposal', ['Save your copy of the supplied proposal.', 'Replace the names and proposed service area. Leave unagreed terms clearly marked.', 'Check responsibilities and the separate spend approval before sharing it yourself.']),
    task('Deliver a mock campaign', 'report', ['Walk through the simulated delivery checklist.', 'Read the sample report: enquiries and booked jobs are different measures.', 'Open your saved advert, page, offer and proposal. Your starter project is ready to keep improving.']),
  ];
}
