export type ColorScheme = 'light' | 'dark';

export const nativeTheme = {
  colors: {
    light: {
      background: '#F4F0E8',
      foreground: '#1B1D1A',
      border: '#D8D1C3',
      card: '#FCFAF5',
      cardForeground: '#1B1D1A',
      primary: '#D97745',
      primaryForeground: '#1B1D1A',
      secondary: '#8FA58A',
      secondaryForeground: '#1B1D1A',
      muted: '#E9E4DA',
      mutedForeground: '#687067',
      accent: '#E8B45B',
      accentForeground: '#1B1D1A',
      destructive: '#B8493D',
      destructiveForeground: '#FCFAF5',
      input: '#D8D1C3',
      sidebar: '#1B1D1A',
      sidebarForeground: '#F4F0E8',
    },
    dark: {
      background: '#171A19',
      foreground: '#F4F0E8',
      border: '#3B4039',
      card: '#202521',
      cardForeground: '#F4F0E8',
      primary: '#E7A07B',
      primaryForeground: '#171A19',
      secondary: '#8FA58A',
      secondaryForeground: '#171A19',
      muted: '#2D332D',
      mutedForeground: '#B7BBAF',
      accent: '#E8B45B',
      accentForeground: '#171A19',
      destructive: '#E26B5E',
      destructiveForeground: '#171A19',
      input: '#3B4039',
      sidebar: '#101211',
      sidebarForeground: '#F4F0E8',
    },
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    xxxl: 40,
  },
  typography: {
    sans: {
      regular: 'Inter_400Regular',
      medium: 'Inter_500Medium',
      semibold: 'Inter_600SemiBold',
      bold: 'Inter_700Bold',
      extrabold: 'Inter_800ExtraBold',
    },
    serif: 'Georgia',
    mono: 'Menlo',
  },
} as const;

export type NativeTheme = typeof nativeTheme;