import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { ScreenShell } from '@/components/path-ui';
import { normalizeProfile, useProgress, type OnboardingProfile } from '@/context/progress';

export default function ProgrammeSettings() {
  const { profile, setProfile } = useProgress(); const router = useRouter();
  const [draft, setDraft] = useState(() => ({ ...normalizeProfile(profile), businessRoute: profile?.businessRoute ?? 'service', dietStyle: profile?.dietStyle ?? 'mixed' }));
  const options = <K extends keyof OnboardingProfile>(key: K, title: string, values: [OnboardingProfile[K], string, string][]) => <View style={s.group}><Text style={s.title}>{title}</Text>{values.map(([value, label, detail]) => <Pressable key={String(value)} accessibilityRole="radio" accessibilityState={{ selected: draft[key] === value }} onPress={() => setDraft({ ...draft, [key]: value })} style={[s.option, draft[key] === value && s.selected]}><View style={{ flex: 1 }}><Text style={s.label}>{label}</Text><Text style={s.body}>{detail}</Text></View><Feather name={draft[key] === value ? 'check-circle' : 'circle'} size={20} color="#A998FF" /></Pressable>)}</View>;
  return <ScreenShell><View style={s.page}><Pressable accessibilityRole="button" onPress={() => router.canGoBack() ? router.back() : router.replace('/')} style={s.back}><Feather name="arrow-left" size={20} color="#F6FBFF" /><Text style={s.label}>Back to my plan</Text></Pressable><Text style={s.heading}>Make the plan fit.</Text><Text style={s.body}>Your current session stays saved. Each foundation contains seven assignments, completed at your pace.</Text>
    {options('focusTrack', 'Your main goal', [['freedom', 'Financial Freedom', 'A business project with concrete milestones.'], ['mind', 'Think more clearly', 'Ideas applied to everyday decisions.'], ['body', 'Build physical foundations', 'Movement and practical nutrition.']])}
    {options('time', 'Your daily time', [['ten', 'About 10 minutes', 'Three short quests: read, move, build.'], ['twenty', 'About 20 minutes', 'A balanced mix across all three paths.'], ['forty', 'Up to 40 minutes', 'Three main sessions, about 30 minutes total.']])}
    {options('businessRoute', 'Your Financial Freedom programme', [['service', 'Service business / SMMA', 'Recommended starting route: make a sample before buying tools.'], ['saas', 'SaaS', 'Validate a recurring problem, then specify one feature.'], ['app', 'Your own app', 'Test a workflow before building a full app.']])}
    {options('dietStyle', 'Your Body meal examples', [['mixed', 'Mixed diet', 'Plant and animal protein alternatives.'], ['vegetarian', 'Vegetarian', 'Plant foods and suitable dairy.'], ['plant', 'Plant-based', 'Beans and lentils as the example proteins.']])}
    <Text style={s.body}>Check meal ingredients for allergies and religious requirements; follow any prescribed diet. Movement restrictions come from onboarding.</Text>
    <Pressable accessibilityRole="button" onPress={() => { setProfile(draft); router.replace('/'); }} style={s.save}><Text style={s.saveText}>Save my programme</Text><Feather name="arrow-right" size={20} color="#08121D" /></Pressable>
  </View></ScreenShell>;
}
const s = StyleSheet.create({ page: { maxWidth: 640, width: '100%', alignSelf: 'center', paddingHorizontal: 22 }, back: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 10 }, heading: { color: '#F6FBFF', fontSize: 31, fontWeight: '700', marginTop: 20 }, title: { color: '#F6FBFF', fontSize: 18, fontWeight: '600', marginBottom: 8 }, body: { color: '#A7BBC9', fontSize: 13, lineHeight: 21, marginTop: 6 }, label: { color: '#F6FBFF', fontSize: 15 }, group: { marginTop: 28 }, option: { minHeight: 64, padding: 16, borderRadius: 15, backgroundColor: '#112536', borderWidth: 1, borderColor: '#284255', flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 9 }, selected: { borderColor: '#A998FF', backgroundColor: '#25243F' }, save: { minHeight: 56, padding: 18, borderRadius: 16, backgroundColor: '#A998FF', marginTop: 25, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, saveText: { color: '#08121D', fontSize: 16, fontWeight: '700' } });
