// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/onboarding/OnboardingFlow.tsx": () => import("../components/mockups/onboarding/OnboardingFlow.tsx"),
  "./components/mockups/onboarding/steps/EquipmentAccessStep.tsx": () => import("../components/mockups/onboarding/steps/EquipmentAccessStep.tsx"),
  "./components/mockups/onboarding/steps/ExperienceLevelStep.tsx": () => import("../components/mockups/onboarding/steps/ExperienceLevelStep.tsx"),
  "./components/mockups/onboarding/steps/FitnessGoalStep.tsx": () => import("../components/mockups/onboarding/steps/FitnessGoalStep.tsx"),
  "./components/mockups/onboarding/steps/WorkoutDurationStep.tsx": () => import("../components/mockups/onboarding/steps/WorkoutDurationStep.tsx"),
  "./components/mockups/onboarding/steps/WorkoutFrequencyStep.tsx": () => import("../components/mockups/onboarding/steps/WorkoutFrequencyStep.tsx")
};
